version: "3"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://json-server:8000
    depends_on:
      - json-server

  json-server:
    build:
      context: ./json-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./json-server/db.json:/app/db.json
